// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeImage(arg1, arg2, arg3) {
  return window['go']['main']['App']['AnalyzeImage'](arg1, arg2, arg3);
}

export function AnalyzeText(arg1, arg2, arg3) {
  return window['go']['main']['App']['AnalyzeText'](arg1, arg2, arg3);
}

export function Extract(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Extract'](arg1, arg2, arg3, arg4, arg5);
}

export function Generate(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['Generate'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}
