// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {stego} from '../models';
import {main} from '../models';

export function AnalyzeImage(arg1:string,arg2:string,arg3:string):Promise<stego.AnalysisResult>;

export function AnalyzeText(arg1:string,arg2:string,arg3:string):Promise<stego.AnalysisResult>;

export function Extract(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:string):Promise<main.ExtResult>;

export function Generate(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean,arg8:string):Promise<main.GenResult>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;
